### PR TITLE
[WIP] Fix/issue 61

### PR DESCRIPTION
**Pull request by scheffsn-dev**
#### Short Description
Fixes issue #61 
Removed spaces in CSAR file name during the upload process.
File names passed to the private **handleCsarUpload** method will be checked for spaces and replaced with an empty string.
#### Proposed Changes

**Fixes**: #61

Tested with My Tiny Todo.

### CODE REVIEW

**Comment by Vogel612** [comment]
I'd prefer a replacement with "_".

**Comment by nyuuyn** [comment]
One of the problems is that the CSAR filename is used often in ID's for variables in the generated BPEL Workflows and ID's normally are NCNames (https://www.w3.org/TR/REC-xml-names/#NT-NCName, https://stackoverflow.com/a/6159003), which basically doesn't allow to use spaces. 

So a proper fix is either changing/removing spaces in CSAR Filenames or changing the ID generation, which will have to be fixed by a (possible) plethora of changes.
Additionally, we not just use the name for IDs, e.g., we copy many files unto VM's that are found by using the CSAR filename, I can't guarantee that this will not have side effects, that have to be fixed as well.

**Comment by miwurster** [comment]
Is this PR then obsolete due to #75 ?

**Comment by scheffsn-dev** [comment]
No, it's not. #75 is just the utility that will be used to fix this issue. Since we decided now what utility will be used, we can continue working on this issue.

**Comment by miwurster** [comment]
If this PR is ready to review, please tag it with "needs review". Thanks.

**Pull request closed without merging**
