### PR TITLE
Fix/loggingnullpointer

### PR DESCRIPTION
**Pull request by nyuuyn**
#### Short Description
On some machines the docker container of the runtime could't properly start because of issues within the logging framework (see #150)

#### Proposed Changes
  * remove (unnecessary?) logging context configuration within WAR project

**Fixes**: #150

### CODE REVIEW

**Comment by nyuuyn** [comment]
Well, it seems like this is NOT the fix 🗡️

**Comment by Vogel612** [comment]
Logging should be the first configuration thing during startup. From the error log it seems to be an issue around using slf4j and logback in conjunction. Something that might be worth investigating is removing one of these logging frameworks in favor of some kind of logging bridge.

The logback docs suggest that we should prefer logback over slf4j.

**Comment by nyuuyn** [comment]
After multiple tests now on bwCloud, the current branch should fix the problem

**Review by wederbn — APPROVED** [review]

**Comment by nyuuyn** [comment]
fixes #56

**Pull request merged**
