### PR TITLE
Fix/scaleoutplans

### PR DESCRIPTION
**Pull request by nyuuyn**
#### Short Description
fixes issue with duplicate activities in scale out order graph
fixes issue with selecting nodes in the right service instance

### CODE REVIEW

**Comment by nyuuyn** [comment]
We need to revisit termination plans to be able merge this, as termination plans have a slight conceptual issue

**Comment by nyuuyn** [comment]
@wederbn any idea what was going on here ?

**Comment by wederbn** [comment]
Somehow the problem that the termination plan tries to terminate the first instance multiple times if mutliple instances are created through scale out was related to this PR as far as I remember 😅

**Comment by nyuuyn** [comment]
:eyes:

**Pull request closed without merging**
